# -*- coding: utf-8 -*-
"""GreedyATM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rwtPE9cLKM8vww3WZmuFKfYy1UsqK08A
"""

def withdrawal(amount, denomination):
    sorted_papers = sorted(denomination, reverse=True)
    change = []

    for papers in sorted_papers:
        while amount >= papers:
            change.append(papers)
            amount -= papers

    return change

def hitung_total(Paper):
    total = 0
    for i in Paper:
        total = total + i
    return total


# Example usage:
denominations = [100, 50, 20, 10, 5]
withdraw_amount = int(input("Please input the amount you want to withdraw : "))


Paper = withdrawal(withdraw_amount, denominations)
total = hitung_total(Paper)

print("Uang:", *Paper)
print("Banyak lembaran : ", len(Paper))
print("Total uang : ", total, "Ribu Rupiah")